name: Atualizar código com OpenAI

on:
  workflow_dispatch:

jobs:
  atualizar_arquivo:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repositório
      uses: actions/checkout@v3

    - name: Rodar Script Python com OpenAI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      run: |
        python3 <<EOF
        import os
        import requests
        import base64
        import openai

        openai.api_key = os.getenv("OPENAI_API_KEY")
        repo = os.getenv("GITHUB_REPOSITORY")
        token = os.getenv("TOKEN_GITHUB")
        arquivo = "index.html"
        branch = "main"

        prompt = "Crie um código HTML com estilo medieval para uma loja fictícia chamada Divina Opção com botão Entrar."

        resposta = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1000,
            temperature=0.6
        )

        codigo_gerado = resposta['choices'][0]['message']['content']

        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }

        url_get = f"https://api.github.com/repos/{repo}/contents/{arquivo}?ref={branch}"
        resposta_get = requests.get(url_get, headers=headers)
        sha = resposta_get.json().get('sha') if resposta_get.status_code == 200 else None

        conteudo_base64 = base64.b64encode(codigo_gerado.encode()).decode()

        data = {
            "message": "Atualizar index.html com código gerado pelo ChatGPT",
            "content": conteudo_base64,
            "branch": branch
        }
        if sha:
            data["sha"] = sha

        url_put = f"https://api.github.com/repos/{repo}/contents/{arquivo}"
        resposta_put = requests.put(url_put, headers=headers, json=data)

        if resposta_put.status_code in [200, 201]:
            print("✔️ Arquivo atualizado com sucesso!")
        else:
            print("❌ Erro ao atualizar:", resposta_put.text)
        EOF
